version: "3.7"

services:
  get5-web:
    build: .
    restart: always
    depends_on:
      - mysql
    ports:
      - 127.0.0.1:8080:80
    environment:
      - SQLALCHEMY_DATABASE_URI=${SQLALCHEMY_DATABASE_URI}
      - STEAM_API_KEY=${STEAM_API_KEY}
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_KEY=${DATABASE_KEY}
      - WEBPANEL_NAME=${WEBPANEL_NAME}
      - MAPLIST=${MAPLIST}
      - DEFAULT_MAPLIST=${DEFAULT_MAPLIST}
      - GET5_URL_OVERRIDE=${GET5_URL_OVERRIDE}
      - ADMIN_IDS=${ADMIN_IDS}
      - SUPER_ADMIN_IDS=${SUPER_ADMIN_IDS}
      - WHITELISTED_IDS=${WHITELISTED_IDS}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASS}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_USER_PASS}

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASS}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_USER_PASS}
    ports:
      - 3306:3306
